"""user avatar

Revision ID: b3a3dab8f001
Revises: 
Create Date: 2019-04-10 15:21:32.832702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a3dab8f001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.drop_column('user', 'thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('thumbnail', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('user', 'avatar')
    # ### end Alembic commands ###
