###########
# BUILDER #
###########

# base image
FROM node:11.6.0-alpine as builder

# set working directory
WORKDIR /usr/src/app/

# install app dependencies
ENV PATH /usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install --silent --no-cache

# set environment variables
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

# create build
ADD . /usr/src/app
RUN npm run build
RUN ls .

#########
# FINAL #
#########

# base image
FROM nginx:1.15.8-alpine

# copy static files
COPY --from=builder /usr/src/app/dist /usr/share/nginx/html

# expose port
EXPOSE 80

# run nginx
CMD ["nginx", "-g", "daemon off;"]
