FROM node:11.6.0-alpine

WORKDIR /usr/src/app/

COPY package.json ./
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install --silent --no-cache

COPY ./ ./


CMD ["npm", "run", "start"]
